### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by tladesignz**

### CODE REVIEW

**Comment by tladesignz** [comment]
Update to latest Keanu with 2 replaced storyboards.

**Comment by N-Pex** [comment]
Thanks, merged now!

**Comment by tladesignz** [comment]
I updated the Config.xcconfig as in recent Keanu. Makes it easier to change stuff for development. Be sure to revisit that!

**Comment by N-Pex** [comment]
Yup, saw that, did that =)

**Pull request merged**
